import streamlit as st
st.title ('skdml cjt dnpq tjqltm akemfrl')
a=st. text_input('이름을 입력하세요')
b=st.selectbox('좋아하는 음식을 선택하시오',['마라탕','치킨','떡'])
if st.button( '인사말 생성')
st.write(a+'님, 안녕하세요')
st.info('반갑습니다')
st.warning(b+'음식을 좋아하시나 봐요')
st.error('잘부탁 드립니다')
st.ballons()
